# This is a data file that contains information describing the text that is
# displayed on pages in the Lang section of Sonic Pi's help panel.

## Function name
## ====================
# A unique identifier for this function.
["load_buffer"]

## Function summary
## ====================
# A short phrase describing this Sonic Pi function.
summary = "Load the contents of a file to the current buffer"

## Function description
## ====================
# The detailed description of this function.
doc = '''
Given a path to a file, will read the contents and load it into the current buffer. This will replace any previous content.
'''

## Function args
## ====================
# Args are the required parameters for the function. Each arg has two documented
# properties:
# - the arg's name
# - the arg's type (number, integer, symbol, ...).
# Example:
# (Repeat the following for every arg):
# [[chord.args]]
# name = "tonic"
# type = "symbol"

[["load_buffer".args]]
name = "path"
type = "string"

## Function introduction
## ====================
# The label describing the version of Sonic Pi in which this function first appeared.
["load_buffer".introduced]
label = "Introduced in v2.10"

## Function options
## ====================
# The options are the optional parameters of this function.
# Each option has two documented properties:
# - the option's name
# - the option's description doc.
# Example:
# [chord.options]
# label = "Options"

# Now repeat the following for every option:
# [[chord.options.list]]
# name = "invert:"
# doc = '''
# Apply the specified num inversions to chord. See the fn `chord_invert`.
# '''

## Function examples
## ====================
# Each function may have one or more examples. If it has any, they are listed
# under an overall 'Example' or 'Examples' label (heading), and each example has
# a numbered sub-heading.
# Example:
# [chord.examples]
# label = "Example"
# label_plural = "Examples"

# Now repeat the following for every example:
# [[chord.examples.list]]
# label = "Example 1"
# example = '''
# puts (chord :e, :minor) # returns a ring of midi notes - (ring 64, 67, 71)
# '''
["load_buffer".examples]
label = "Example"
label_plural = "Examples"

[["load_buffer".examples.list]]
label = "Example 1"
example = '''

load_buffer "~/sonic-pi-tracks/phat-beats.rb" # will replace content of current buffer with contents of the file
'''

