# This is a data file that contains information describing the text that is
# displayed on pages in the Lang section of Sonic Pi's help panel.

## Function name
## ====================
# A unique identifier for this function.
["midi_reset"]

## Function summary
## ====================
# A short phrase describing this Sonic Pi function.
summary = "Reset MIDI devices"

## Function description
## ====================
# The detailed description of this function.
doc = '''
Sends a MIDI reset all controllers message to *all* connected devices on *all* channels. Use the `port:` and `channel:` opts to restrict which MIDI ports and channels are used.

All controller values are reset to their defaults.

[MIDI 1.0 Specification - Channel Mode Messages - Reset All Controllers](https://www.midi.org/specifications/item/table-1-summary-of-midi-message)

'''

## Function args
## ====================
# Args are the required parameters for the function. Each arg has two documented
# properties:
# - the arg's name
# - the arg's type (number, integer, symbol, ...).
# Example:
# (Repeat the following for every arg):
# [[chord.args]]
# name = "tonic"
# type = "symbol"

[["midi_reset".args]]
name = "value"
type = "number"

## Function introduction
## ====================
# The label describing the version of Sonic Pi in which this function first appeared.
["midi_reset".introduced]
label = "Introduced in v3.0"

## Function options
## ====================
# The options are the optional parameters of this function.
# Each option has two documented properties:
# - the option's name
# - the option's description doc.
# Example:
# [chord.options]
# label = "Options"

# Now repeat the following for every option:
# [[chord.options.list]]
# name = "invert:"
# doc = '''
# Apply the specified num inversions to chord. See the fn `chord_invert`.
# '''

["midi_reset".options]
label = "Options"

[["midi_reset".options.list]]
name = "channel:"
doc = '''
Channel to send the midi reset message to
'''

[["midi_reset".options.list]]
name = "port:"
doc = '''
MIDI port to send to
'''

[["midi_reset".options.list]]
name = "value:"
doc = '''
Value must only be zero (the default) unless otherwise allowed in a specific Recommended Practice
'''

[["midi_reset".options.list]]
name = "on:"
doc = '''
If specified and false/nil/0 will stop the midi reset message from being sent out. (Ensures all opts are evaluated in this call to `midi_reset` regardless of value).
'''

## Function examples
## ====================
# Each function may have one or more examples. If it has any, they are listed
# under an overall 'Example' or 'Examples' label (heading), and each example has
# a numbered sub-heading.
# Example:
# [chord.examples]
# label = "Example"
# label_plural = "Examples"

# Now repeat the following for every example:
# [[chord.examples.list]]
# label = "Example 1"
# example = '''
# puts (chord :e, :minor) # returns a ring of midi notes - (ring 64, 67, 71)
# '''
["midi_reset".examples]
label = "Example"
label_plural = "Examples"

[["midi_reset".examples.list]]
label = "Example 1"
example = '''
midi_reset #=> Reset MIDI devices on all channels (and ports)
'''

[["midi_reset".examples.list]]
label = "Example 2"
example = '''
midi_reset channel: 2 #=> Reset MIDI devices on channel 2
'''

