# This is a data file that contains information describing the text that is
# displayed on pages in the Synths and FX sections of Sonic Pi's help panel.

## Synth or FX name
## ====================
# A unique identifier for this synth or FX.
["eq"]

## Synth or FX long name
## ====================
# A word or short phrase that is used as a label for the synth or FX.
name = "EQ"

## Synth or FX usage example
## ====================
# A basic code example of how to use the synth or FX.
usage = '''
with_fx :eq do
  play 50
end
'''

## Synth or FX description
## ====================
# The detailed description of the synth or FX.
doc = '''
Basic parametric EQ
'''

## Synth or FX introduction
## ====================
# The label describing the version of Sonic Pi in which this synth or FX first appeared.
["eq".introduced]
label = "Introduced in v3.0"

## Synth or FX options
## ====================
# The options are the opts of this synth or FX.
# In the documentation, we currently display two tables of opts:
# - one listing the name of each opt and its default value for easy reference
# - a second, more detailed table labelled 'Options', containing:
#   - the name of each opt
#   - a detailed description of it
#   - its default value
#   - (if the opt has constraints (limits or a specific range of permitted
#     values, etc)): the constraints of the opt.
#     Example:
#     contraints = '''
#     Must be zero or greater
#     '''
#   - a label describing whether this opt can be modulated (altered) while the
#     synth or fx is running
#   - (if the opt is slidable): a label indicating that the opt is slidable.
#     Example:
#     slidable_label = "Has slide options to shape changes"
#   - (if the opt is affected by the current BPM): a label indicating that the opt is scaled with the current BPM.
#     Example:
#     bpm_scaled_label = "Scaled with current BPM value"
["eq".options]
label = "Options"

[["eq".options.list]]
name = "amp:"
doc = '''
The amplitude of the sound. Typically a value between 0 and 1. Higher amplitudes may be used, but won't make the sound louder, they will just reduce the quality of all the sounds currently being played (due to compression.)
'''
default_value = "1"
constraints = '''
Must be zero or greater
'''
modulatable = '''
May be changed whilst playing
'''
slidable_label = "Has slide options to shape changes"

[["eq".options.list]]
name = "mix:"
doc = '''
The amount (percentage) of FX present in the resulting sound represented as a value between 0 and 1. For example, a mix of 0 means that only the original sound is heard, a mix of 1 means that only the FX is heard (typically the default) and a mix of 0.5 means that half the original and half of the FX is heard.
'''
default_value = "1"
constraints = '''
Must be a value between 0 and 1 inclusively
'''
modulatable = '''
May be changed whilst playing
'''
slidable_label = "Has slide options to shape changes"

[["eq".options.list]]
name = "pre_mix:"
doc = '''
The amount (percentage) of the original signal that is fed into the internal FX system as a value between 0 and 1. With a pre_mix: of 0 the FX is completely bypassed unlike a mix: of 0 where the internal FX is still being fed the original signal but the output of the FX is ignored. The difference between the two is subtle but important and is evident when the FX has a residual component such as echo or reverb. When switching mix: from 0 to 1, the residual component of the FX's output from previous audio is present in the output signal. With pre_mix: there is no residual component of the previous audio in the output signal.
'''
default_value = "1"
constraints = '''
Must be zero or greater
'''
modulatable = '''
May be changed whilst playing
'''
slidable_label = "Has slide options to shape changes"

[["eq".options.list]]
name = "pre_amp:"
doc = '''
Amplification applied to the input signal immediately before it is passed to the FX.
'''
default_value = "1"
constraints = '''
Must be zero or greater
'''
modulatable = '''
May be changed whilst playing
'''
slidable_label = "Has slide options to shape changes"

[["eq".options.list]]
name = "low_shelf:"
doc = '''
Gain - boost or cut the centre frequency. The low shelf defines the characteristics of the lowest part of the eq FX. A value of 0 will neither boost or cut the low_shelf frequencies. A value of 1 will boost by 15 dB and a value of -1 will cut/attenuate by -15 dB.
'''
default_value = "0"
modulatable = '''
May be changed whilst playing
'''
slidable_label = "Has slide options to shape changes"

[["eq".options.list]]
name = "low_shelf_note:"
doc = '''
Centre frequency of low shelf in MIDI notes.
'''
default_value = "43.349957"
constraints = '''
Must be a value greater than 1
'''
modulatable = '''
May be changed whilst playing
'''
slidable_label = "Has slide options to shape changes"

[["eq".options.list]]
name = "low_shelf_slope:"
doc = '''
Low shelf boost/cut slope. When set to 1 (the default), the shelf slope is as steep as it can be and remain monotonically increasing or decreasing gain with frequency.
'''
default_value = "1"
constraints = '''
Must be a value greater than or equal to 0, must be a value less than or equal to 1
'''
modulatable = '''
May be changed whilst playing
'''
slidable_label = "Has slide options to shape changes"

[["eq".options.list]]
name = "low:"
doc = '''
Gain - boost or cut the centre frequency of the bass part of the sound. The low shelf defines the characteristics of the bass of the eq FX. A value of 0 will neither boost or cut the bass frequencies. A value of 1 will boost by 15 dB and a value of -1 will cut/attenuate by -15 dB.
'''
default_value = "0"
modulatable = '''
May be changed whilst playing
'''
slidable_label = "Has slide options to shape changes"

[["eq".options.list]]
name = "low_note:"
doc = '''
Centre frequency of the low eq parameter in MIDI notes.
'''
default_value = "59.2130948"
constraints = '''
Must be a value greater than 1
'''
modulatable = '''
May be changed whilst playing
'''
slidable_label = "Has slide options to shape changes"

[["eq".options.list]]
name = "low_q:"
doc = '''
The Q factor for the low eq parameter.

The Q factor controls the width of frequencies that will be affected by the low parameter of this eq FX. A low Q factor gives a wide bandwidth affecting a larger range of frequencies. A high Q factor will give a narrow bandwidth affecting a much smaller range of frequencies.

Here's a list of various Q factors and an approximate corresponding frequency width:

0.7     -> 2 octaves
1       -> 1 1/3 octaves
1.4     -> 1 octave
2.8     -> 1/2 octave
4.3     -> 1/3 octave
8.6     -> 1/6 octave

A decent range of Q factors for naturally sounding boosts/cuts is 0.6 to 1.

'''
default_value = "0.6"
constraints = '''
Must be a value greater than or equal to 0.001, must be a value less than or equal to 100
'''
modulatable = '''
May be changed whilst playing
'''
slidable_label = "Has slide options to shape changes"

[["eq".options.list]]
name = "mid:"
doc = '''
Gain - boost or cut the centre frequency of the middle part of the sound. The mid shelf defines the characteristics of the bass of the eq FX. A value of 0 will neither boost or cut the bass frequencies. A value of 1 will boost by 15 dB and a value of -1 will cut/attenuate by -15 dB.
'''
default_value = "0"
modulatable = '''
May be changed whilst playing
'''
slidable_label = "Has slide options to shape changes"

[["eq".options.list]]
name = "mid_note:"
doc = '''
Centre frequency of the mid eq parameter in MIDI notes.
'''
default_value = "83.2130948"
constraints = '''
Must be a value greater than 1
'''
modulatable = '''
May be changed whilst playing
'''
slidable_label = "Has slide options to shape changes"

[["eq".options.list]]
name = "mid_q:"
doc = '''
The Q factor for the mid eq parameter.

The Q factor controls the width of frequencies that will be affected by the mid parameter of this eq FX. A mid Q factor gives a wide bandwidth affecting a larger range of frequencies. A high Q factor will give a narrow bandwidth affecting a much smaller range of frequencies.

Here's a list of various Q factors and an approximate corresponding frequency width:

0.7     -> 2 octaves
1       -> 1 1/3 octaves
1.4     -> 1 octave
2.8     -> 1/2 octave
4.3     -> 1/3 octave
8.6     -> 1/6 octave

A decent range of Q factors for naturally sounding boosts/cuts is 0.6 to 1.

'''
default_value = "0.6"
constraints = '''
Must be a value greater than or equal to 0.001, must be a value less than or equal to 100
'''
modulatable = '''
May be changed whilst playing
'''
slidable_label = "Has slide options to shape changes"

[["eq".options.list]]
name = "high:"
doc = '''
Gain - boost or cut the centre frequency of the high part of the sound. The high shelf defines the characteristics of the treble of the eq FX. A value of 0 will neither boost or cut the treble frequencies. A value of 1 will boost by 15 dB and a value of -1 will cut/attenuate by -15 dB.
'''
default_value = "0"
modulatable = '''
May be changed whilst playing
'''
slidable_label = "Has slide options to shape changes"

[["eq".options.list]]
name = "high_note:"
doc = '''
Centre frequency of the high eq parameter in MIDI notes.
'''
default_value = "104.9013539"
constraints = '''
Must be a value greater than 1
'''
modulatable = '''
May be changed whilst playing
'''
slidable_label = "Has slide options to shape changes"

[["eq".options.list]]
name = "high_q:"
doc = '''
The Q factor for the high eq parameter.

The Q factor controls the width of frequencies that will be affected by the high parameter of this eq FX. A high Q factor gives a wide bandwidth affecting a larger range of frequencies. A high Q factor will give a narrow bandwidth affecting a much smaller range of frequencies.

Here's a list of various Q factors and an approximate corresponding frequency width:

0.7     -> 2 octaves
1       -> 1 1/3 octaves
1.4     -> 1 octave
2.8     -> 1/2 octave
4.3     -> 1/3 octave
8.6     -> 1/6 octave

A decent range of Q factors for naturally sounding boosts/cuts is 0.6 to 1.

'''
default_value = "0.6"
constraints = '''
Must be a value greater than or equal to 0.001, must be a value less than or equal to 100
'''
modulatable = '''
May be changed whilst playing
'''
slidable_label = "Has slide options to shape changes"

[["eq".options.list]]
name = "high_shelf:"
doc = '''
Gain - boost or cut the centre frequency. The high shelf defines the characteristics of the highest part of the eq FX. A value of 0 will neither boost or cut the high_shelf frequencies. A value of 1 will boost by 15 dB and a value of -1 will cut/attenuate by -15 dB.
'''
default_value = "0"
modulatable = '''
May be changed whilst playing
'''
slidable_label = "Has slide options to shape changes"

[["eq".options.list]]
name = "high_shelf_note:"
doc = '''
Centre frequency of high shelf in MIDI notes.
'''
default_value = "114.2326448"
constraints = '''
Must be a value greater than 1
'''
modulatable = '''
May be changed whilst playing
'''
slidable_label = "Has slide options to shape changes"

[["eq".options.list]]
name = "high_shelf_slope:"
doc = '''
High shelf boost/cut slope. When set to 1 (the default), the shelf slope is as steep as it can be and remain monotonically increasing or decreasing gain with frequency.
'''
default_value = "1"
constraints = '''
Must be a value greater than or equal to 0, must be a value less than or equal to 1
'''
modulatable = '''
May be changed whilst playing
'''
slidable_label = "Has slide options to shape changes"

## Sample sliding
## ====================
# The values set below relate to the documentation section on sliding,
# that describes what sliding options are, and what each of them do.
["eq".sliding]
slide_label = "Slide Options"
slide_description = '''
Any parameter that is slidable has three additional options named _slide,
_slide_curve, and _slide_shape.  For example, 'amp' is slidable, so you can also
set amp_slide, amp_slide_curve, and amp_slide_shape with the following effects:
'''

[["eq".sliding.slide_opts]]
name = "_slide"
default = "0"
doc = '''
Amount of time (in beats) for the parameter value to change. A long parameter_slide value means that the parameter takes a long time to slide from the previous value to the new value. A parameter_slide of 0 means that the parameter instantly changes to the new value.
'''

[["eq".sliding.slide_opts]]
name = "_slide_shape"
default = "5"
doc = '''
Shape of curve. 0: step, 1: linear, 3: sine, 4: welch, 5: custom (use *_slide_curve: opt e.g. amp_slide_curve:), 6: squared, 7: cubed. 
'''

[["eq".sliding.slide_opts]]
name = "_slide_curve"
default = "0"
doc = '''
Shape of the slide curve (only honoured if slide shape is 5). 0 means linear and positive and negative numbers curve the segment up and down respectively.
'''


